'use client';

import React, { forwardRef, useEffect, useState } from 'react';
import type { ReportEntry } from '@/lib/reports';
import { Icons } from '@/components/icons/Icons';

interface ReportCanvasProps {
  report: ReportEntry | null;
  isFullscreen: boolean;
  onExitFullscreen: () => void;
}

/**
 * Area render laporan HTML. File dimuat via iframe agar CSS/JS laporan
 * tidak bentrok dengan styling dashboard.
 * Ref diarahkan ke <iframe> supaya parent bisa memanggil print().
 */
export const ReportCanvas = forwardRef<HTMLIFrameElement, ReportCanvasProps>(
  function ReportCanvas({ report, isFullscreen, onExitFullscreen }, iframeRef) {
    const [isFrameLoading, setIsFrameLoading] = useState(true);

    // Tampilkan loader setiap kali edisi berganti
    useEffect(() => {
      setIsFrameLoading(true);
    }, [report?.url]);

    if (!report) {
      return (
        <div className="viewer-empty">
          {Icons.layers}
          <h1>No Briefing Reports Available</h1>
          <p>
            Drop <code>.html</code> reports generated by AI into the <code>public/reports/</code> directory,
            then click the refresh button at the top right.
          </p>
          <p className="viewer-empty-hint">
            Recommended filename format: <code>YYYY-MM-DD_report-title.html</code>
          </p>
        </div>
      );
    }

    return (
      <div className="viewer-canvas">
        {isFrameLoading && (
          <div className="viewer-loader" role="status">
            <span className="viewer-loader-bar" />
            <span>Loading briefing report…</span>
          </div>
        )}

        <iframe
          key={report.url}
          ref={iframeRef}
          src={report.url}
          title={report.title}
          className="viewer-frame"
          onLoad={() => setIsFrameLoading(false)}
          sandbox="allow-scripts allow-same-origin allow-popups allow-modals allow-downloads allow-forms"
        />

        {isFullscreen && (
          <button
            id="exitFullscreen"
            className="viewer-exit-fullscreen"
            onClick={onExitFullscreen}
            aria-label="Exit fullscreen"
          >
            {Icons.collapse} Exit <kbd>Esc</kbd>
          </button>
        )}
      </div>
    );
  }
);
